name: Pull request workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          . tests.sh
